databases:
  - name: shortly
    plan: free
    databaseName: shortly_y73u
    user: shortly_y73u_user

services:
  - type: web
    plan: free
    name: urlShortener
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn urlShortener.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shortly
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
